name: canti_scout
description: Canti Scout - cantare insieme mai stato così facile

#
# BUILD WITH
# flutter build apk --build-name=5.0.0 --build-number=1
#
version: 5.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  share_plus: ^10.1.4
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.3.3
  wakelock_plus: ^1.2.10
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  file_picker: ^11.0.2
  path: ^1.9.0
  archive: ^4.0.9
  pdf: ^3.10.8
  flutter_blue_plus: ^2.2.1
  ble_peripheral: ^2.4.0
  permission_handler: ^12.0.1

dependency_overrides:
  ble_peripheral:
    path: packages/ble_peripheral

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/image_path_android.png"
  image_path_ios: "assets/images/image_path_ios.png"
  adaptive_icon_background: "assets/images/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg

  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata-Bold.ttf
    - family: Monofur
      fonts:
        - asset: fonts/monof55.ttf
        - asset: fonts/monof55.ttf
          weight: 700
    - family: NotCourierSans
      fonts:
        - asset: fonts/NotCourierSans.otf
        - asset: fonts/NotCourierSans-Bold.otf
          weight: 700
    - family: CaveatBrush
      fonts:
        - asset: fonts/CaveatBrush-Regular.ttf
        - asset: fonts/CaveatBrush-Regular.ttf
          weight: 700
    - family: Neucha
      fonts:
        - asset: fonts/Neucha.ttf
        - asset: fonts/Neucha.ttf
          weight: 700
